### ISSUE TITLE
Geocoding, when you open the page like a file

### ISSUE THREAD

**Issue by hclubmk** [perliedman/leaflet-control-geocoder#145] opened 2016-10-07 13:39 UTC
If a page is opened as a web page, geocoding occurs, but if the page open as file from the local machine, geocoding does not happen, even though routing is built in both cases. 
Is it possible to solve the problem geocoding when opening pages as a file?

Web-page
![Image of Web-page](http://s015.radikal.ru/i331/1610/0a/83535d07e36f.png)

Local file
![Image of Local file](http://s018.radikal.ru/i519/1610/6e/c1f6bc38ba70.png)

**Comment by perliedman** [comment] 2016-10-07 14:16
Currently, you either have to run over http/https, or you can manually specify the protocol to use in the geocoder's `serviceUrl` option.

Duplicate of #30, #68, #108, #125. See them for more info.

**Closed by perliedman** 2016-10-07 14:16 UTC

**Comment by hclubmk** [comment] 2016-10-07 14:50
Thanks, now it works fine!
