### ISSUE TITLE
Clicking on a result item passes the click event onto the map

### ISSUE THREAD

**Issue by markhorgan** [perliedman/leaflet-control-geocoder#142] opened 2016-09-05 10:43 UTC
When clicking on the drop down results, the click event is passed onto the map.

On line 206 of control.js I've changed:

`L.DomEvent.addListener(li, 'mousedown', clickHandler, this);`

to

`L.DomEvent.addListener(li, 'click', clickHandler, this);`

which resolves the issue. 

On line 189 of control.js:
```
clickHandler = function clickHandler(e) {
  L.DomEvent.preventDefault(e);
  this._geocodeResultSelected(result);
};
```

preventDefault(e) prevents the `mousedown` event propagating but not the `click` event. I'm not sure if this is the best way to resolve it. 

I'm working with the version 1.5.1

**Comment by perliedman** [comment] 2016-09-06 10:28
If I remember correctly, we use `mousedown` instead of `click` since some browsers fire `blur` before the click, which then hides the dropdown before the click event is fired.

It might be that this has been fixed by some other change, but we'll have to test.

Another option would be to leave the `mousedown` listener, but also add a `click` listener that simple does `L.DomEvent.preventDefault(e)`.

**Comment by jcoupey** [comment] 2016-09-07 12:51
I'm experiencing the same trouble, and it also occurs when clicking in the search area to gain focus. I'm using version 1.5.1 too.

Odd enough, I recall using a previous version (don't remember which) along with leaflet 1.0.0-beta.2 without this problem.

**Comment by perliedman** [comment] 2016-09-08 07:14
Which Leaflet version are you using? I'm thinking this might be some issue that differs between 0.7 and 1.0.0, but just guessing.

**Comment by perliedman** [comment] 2016-09-08 07:15
@jcoupey @markhorgan can you reproduce the problem in the simple demo (http://www.liedman.net/leaflet-control-geocoder/)?

**Comment by jcoupey** [comment] 2016-09-08 07:32
@perliedman the online demo you linked to works just fine for me with the same browser setting (firefox 48.0).

As for the leaflet version, I though I was using 1.0.0-rc.3 but it seems like I'm actually on 0.7.7 due to the npm dependencies (see #143).

**Comment by perliedman** [comment] 2016-09-08 07:39
Ok, will have to dig into this issue a bit further. Hopefully tomorrow, but I will not promise anything. Help is of course very welcome.

**Comment by jcoupey** [comment] 2016-09-08 08:21
This seems indeed to be leaflet-version related. 

I just checked again using leaflet-control-geocoder 1.5.1. No more click forwarding when using leaflet 1.0.0-beta.2 or 1.0.0-rc.3.

**Comment by domialex** [comment] 2016-09-20 17:53
I also have this problem: leaflet-control-geocoder 1.5.1 and leaflet 1.0.0-rc.3.
http://codepen.io/anon/pen/NRbbLk

**Comment by jcoupey** [comment] 2016-09-21 08:53
@domialex Very odd, I tried your link and I'm not getting any alert box, the geocoder usage is normal. This is in line with my previous attempts with leaflet 1.0.0-rc.3 where everything was fine.

Maybe this is also browser-dependent? I'm using Firefox 48.0.

**Comment by domialex** [comment] 2016-09-21 11:32
I tested and the bug is present in Edge, IE and Chrome. Only Firefox doesn't have the bug. I suggest using click instead of mousedown.

**Comment by perliedman** [comment] 2016-09-21 12:53
@domialex if you read above, the problem with that approach is that it _used to be `click`_, but was changed since it caused problems: https://github.com/perliedman/leaflet-control-geocoder/commit/cc1a049617a3b03a181cb23305dcb297f7f155bf

Can't say for sure if that is still a problem or not, if it's just a problem in some browsers, etc., but I'm wary of just changing this without some thorough testing. Personally, I'm sorry to say that I don't have the time to do that at the moment, but help would be welcome!

**Comment by perliedman** [comment] 2016-10-07 13:55
For me (Chrome 53/Ubuntu 16.04), changing from `mousedown` to `click` does not fix the bug (still get a click event on the map), but also prevents the control from working - you can no longer select a result from the dropdown (presumably since `blur` fires before `click`, so the result is removed before the click can reach it.

**Closed** 2016-10-07 14:10 UTC
