### ISSUE TITLE
Style error on control

### ISSUE THREAD

**Issue by humitos** [perliedman/leaflet-control-geocoder#45] opened 2015-01-16 15:26 UTC
Hi, I noticed a 1pixel-width difference between this control and the others (zoom, for example).

![help-controls](https://cloud.githubusercontent.com/assets/244656/5778528/bc8dd596-9d7a-11e4-9f31-872283353929.jpg)

I don't know enough CSS to fix it. Sorry.

**Comment by ThiagoMVF** [comment] 2015-05-01 22:43
It is caused by .leaflet-control-geocoder-form input padding added by the default browser stylesheets (at least that's what I saw in the ones I've tested). It also caused the control to resize vertically when expanding - should be fixed by the PR ^

**Comment by perliedman** [comment] 2015-05-04 07:21
Fixed by #63.

**Closed by perliedman** 2015-05-04 07:21 UTC
